"""modules/dorking/dorks.py — Dork template library per search type"""

DORK_TEMPLATES = {
    "email": [
        '"{q}"',
        '"{q}" password',
        '"{q}" filetype:sql',
        '"{q}" filetype:txt',
        '"{q}" filetype:csv',
        '"{q}" "password"',
        '"{q}" "passwd"',
        'intext:"{q}" filetype:log',
        'site:pastebin.com "{q}"',
        'site:paste.ee "{q}"',
        'site:justpaste.it "{q}"',
        'site:raidforums.com "{q}"',
        'site:breachforums.st "{q}"',
        'inurl:dump "{q}"',
        '"{q}" "leaked"',
        '"{q}" "@" "pass"',
        'filetype:sql intext:"{q}"',
        'filetype:txt intext:"{q}" intext:password',
    ],
    "username": [
        '"{q}"',
        '"{q}" password',
        '"{q}" "password"',
        'site:pastebin.com "{q}"',
        '"username" "{q}" "password"',
        '"{q}" filetype:txt',
        '"{q}" "leaked"',
        'intext:"{q}" "credentials"',
        'site:raidforums.com "{q}"',
        'site:breachforums.st "{q}"',
    ],
    "password": [
        'password "{q}"',
        '"password" "{q}" filetype:sql',
        'intext:"{q}" site:pastebin.com',
        '"{q}" "username"',
        '"{q}" filetype:txt',
        '"pass" "{q}"',
    ],
    "hash": [
        '"{q}"',
        'site:pastebin.com "{q}"',
        '"{q}" filetype:txt',
        '"{q}" "cracked"',
        'intext:"{q}" "hash"',
    ],
    "name": [
        '"{q}" filetype:csv',
        '"{q}" filetype:xls',
        '"{q}" "email" "phone"',
        'site:pastebin.com "{q}"',
        '"{q}" "address" "email"',
        '"{q}" "date of birth"',
        '"{q}" intext:SSN',
        'intitle:"{q}" "contact"',
    ],
    "ip": [
        '"{q}"',
        'site:pastebin.com "{q}"',
        'intext:"{q}" "port"',
        'intext:"{q}" "exploit"',
        '"{q}" filetype:txt',
        '"{q}" "server" "credentials"',
        'intext:"{q}" "ssh"',
        'intext:"{q}" "rdp"',
    ],
    "domain": [
        'site:pastebin.com "{q}" credentials',
        'intext:"{q}" "password" filetype:sql',
        '"{q}" "username" "password" filetype:txt',
        '"{q}" "db_password"',
        '"{q}" "smtp" "password"',
        'site:{q} filetype:sql',
        'site:{q} filetype:bak',
        'site:{q} filetype:env',
        'site:{q} inurl:config',
        'site:{q} intitle:"index of"',
        '"{q}" "api_key"',
        '"{q}" "secret_key"',
        '"{q}" "access_token"',
        'site:raidforums.com "{q}"',
    ],
    "phone": [
        '"{q}"',
        'intext:"{q}"',
        'site:pastebin.com "{q}"',
        '"{q}" "name" "address"',
        '"{q}" "email"',
    ],
}


def get_dorks(qtype: str, query: str) -> list:
    templates = DORK_TEMPLATES.get(qtype, ['"{q}"'])
    return [t.replace("{q}", query) for t in templates]
